baseURL: https://docte.ch/
title: DocTe.ch

languageCode: fr-ch
defaultContentLanguage: fr

cleandestinationdir: true
copyright: CC by-sa
disableFastRender: true
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: false
removePathAccents: true

author:
  name: Nicolas Friedli
  email: nicolas.friedli+doctech@gmail.com

build:
  writeStats: true

disableKinds:
  - taxonomy
  - term
  - RSS
  - robotsTXT
  - 404

markup:
  goldmark:
    extensions:
      typographer: true
    parser:
      autoHeadingIDType: github-ascii
    renderer:
      unsafe: true
  highlight:
    pygmentsCodefences: true 
    style: dracula

